apiVersion: ipam.k8s.io/v1beta1
kind: IPPool
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ippool-sample
spec:
  dns:
  - 8.8.8.8
  ntp: 1.1.1.1
  reservedAddresses:
  - ipv4: 1.1.1.2
    gateway: 1.1.1.1
    netmask: 255.255.255.0
  - ipv4: 1.1.1.3
    gateway: 1.1.1.1
    netmask: 255.255.255.0
  - ipv4: 1.1.1.4
    gateway: 1.1.1.1
    netmask: 255.255.255.0

